// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haavjhxxptnrlrtmdqub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYXZqaHh4cHRucmxydG1kcXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzEyNTAsImV4cCI6MjA2MjEwNzI1MH0.1GMUMdqLYnZHgchGFdavCUzMXCqfVEVTV-jCyYw-LKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);